### ISSUE TITLE
grouper debrick: Overflow error

### ISSUE THREAD

**Issue by bjo81** [tofurky/tegra30_debrick#14]
Tried to run `./fusee-launcher/fusee-launcher.py ./payload/uart_payload_n7.bin -P 7330 

```
Identified a Linux system; setting up the appropriate backend.
intermezzo_size: 0x00000078
target_payload_size: 0x000005ee
Traceback (most recent call last):
  File "/mnt/home.bjo/n7/tegra30_debrick/./fusee-launcher/fusee-launcher.py", line 718, in <module>
    raise e
  File "/mnt/home.bjo/n7/tegra30_debrick/./fusee-launcher/fusee-launcher.py", line 712, in <module>
    device_id = switch.read_device_id()
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home.bjo/n7/tegra30_debrick/./fusee-launcher/fusee-launcher.py", line 585, in read_device_id
    return self.read(16)
           ^^^^^^^^^^^^^
  File "/mnt/home.bjo/n7/tegra30_debrick/./fusee-launcher/fusee-launcher.py", line 530, in read
    return self.backend.read(length)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home.bjo/n7/tegra30_debrick/./fusee-launcher/fusee-launcher.py", line 134, in read
    return bytes(self.dev.read(0x81, length, 3000))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/usb/core.py", line 1029, in read
    ret = fn(
          ^^^
  File "/usr/lib/python3.12/site-packages/usb/_debug.py", line 62, in do_trace
    return f(*args, **named_args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/usb/backend/libusb1.py", line 846, in bulk_read
    return self.__read(self.lib.libusb_bulk_transfer,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/usb/backend/libusb1.py", line 954, in __read
    _check(retval)
  File "/usr/lib/python3.12/site-packages/usb/backend/libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 75] Overflow
```

**Comment by tofurky** [comment]
using usb3 port?

**Comment by bjo81** [comment]
Yes:
```
[17604.727200] usb 1-6: new high-speed USB device number 78 using xhci_hcd
[17604.868232] usb 1-6: New USB device found, idVendor=0955, idProduct=7330, bcdDevice= 1.03
[17604.868249] usb 1-6: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[17604.868256] usb 1-6: Product: APX
[17604.868262] usb 1-6: Manufacturer: NVIDIA Corp.
``

**Comment by tofurky** [comment]
hmm, no idea then really. maybe try a different PC?

**Comment by tofurky** [comment]
could also try booting an older live distro, maybe something changed with libusb/kernel.

**Comment by bjo81** [comment]
Already tried another system (with another kernel). https://github.com/AndroidRoot/wheelie fails also now when trying to send a bootloader. Maybe I bricked the APX mode when trying to flash uboot? :thinking:

**Comment by tofurky** [comment]
apx isn't really brickable as it's burned into rom on the chip. i hit an issue once with bad odm data being written to bct (bootrom/bootloader config at beginning of flash), but apx mode and fusee were still responsive in that case IIRC. the ODM_DEBRICK define in the payload works around that. i don't think i ever saw an overflow error though, just nvflash not responding after successfully executing fusee.

**Comment by bjo81** [comment]
Maybe it's related to uart_payload_n7.bin, as I also got this error when using it with https://gitlab.com/grate-driver/fusee-tools - but I was able to run fusee-tools with it's own payload and bootloader-grouper-4.23.img so running nvram in resume mode went fine afterwards.

**Comment by tofurky** [comment]
oh, that jogged my memory a bit. i think that can happen if the payload is too big. were you using the one in git or did you compile it yourself?
